M48
; DRILL file {KiCad 9.0.7} date 2026-01-13T15:48:41+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-13T15:48:41+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.854
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.200
%
G90
G05
T1
X78.115Y-45.81
X78.115Y-51.59
T2
X90.8Y-38.75
T3
X160.944Y-38.151
X160.944Y-40.651
T4
X77.0Y-38.0
X77.0Y-74.0
X138.5Y-74.0
X138.75Y-37.75
M30
